variable "cluster_name" {}
variable "repourl" {}
variable "branch" {}
variable "env" {}
variable "host" {}
variable "cluster_ca_certificate" {}
variable "lb_controller_irsa" {}
variable "vpc_id" {}
variable "region" {}
variable "bucket_name" {}
variable "bucket_arn" {}
variable "oidc_provider" {}
variable "db_endpoint" {}
variable "db_username" {}
variable "db_password_secret_arn" {}