apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-flask
spec:
  replicas: {{ .Values.flask.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}-flask
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}-flask
    spec:
      serviceAccountName: {{ include "myapp.fullname" . }}-flask-sa
      containers:
        - name: flask-app
          image: {{ .Values.flask.image }}
          ports:
            - containerPort: {{ .Values.flask.containerPort }}
          resources:
            {{- toYaml .Values.flask.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.flask.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.flask.readinessProbe | nindent 12 }}
