apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-flask-service
spec:
  type: {{ .Values.flask.service.type }}
  selector:
    app: {{ include "myapp.fullname" . }}-flask
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.flask.service.port }}
      targetPort: {{ .Values.flask.containerPort }}