apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "myapp.fullname" . }}-minio-pvc
spec:
  accessModes:
    - {{ .Values.minio.persistentVolumeClaim.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.minio.persistentVolumeClaim.storage | default "1Gi" }}