apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "myapp.fullname" . }}-minio-pv
spec:
  capacity:
    storage: {{ .Values.minio.persistentVolumeClaim.storage | default "1Gi" }}
  accessModes:
    - {{ .Values.minio.persistentVolumeClaim.accessModes | default "ReadWriteOnce" }}
  hostPath:
    path: /mnt/data/minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "myapp.fullname" . }}-minio-pvc
spec:
  accessModes:
    - {{ .Values.minio.persistentVolumeClaim.accessModes | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.minio.persistentVolumeClaim.storage | default "1Gi" }}