apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}-minio
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}-minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: {{ .Values.minio.service.port }}
              name: api
            - containerPort: {{ .Values.minio.containerPort }}
              name: console
          env:
            - name: MINIO_ROOT_USER
              value: "{{ .Values.minio.auth.MINIO_ROOT_USER }}"
            - name: MINIO_ROOT_PASSWORD
              value: "{{ .Values.minio.auth.MINIO_ROOT_PASSWORD }}"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            {{- toYaml .Values.minio.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.minio.readinessProbe | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "myapp.fullname" . }}-minio-pvc