# myapp/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "myapp.fullname" . }}-flask-sa
  namespace: default
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
  annotations:
    # This is a placeholder. Terraform will provide the real ARN.
    eks.amazonaws.com/role-arn: {{ .Values.flask.serviceAccount.roleArn }}