#flask
flask:
  image: danielrabi/flaskapp:1.2.7
  replicaCount: 1
  serviceAccount:
    roleArn: ""
  service:
    type: ClusterIP
    port: 80
  containerPort: 5000
  env:
    DB_HOST: "default-db-host"
    DB_USER: "default-user"
    DB_PASSWORD: "default-password"
    DB_NAME: "default-db-name"
    S3_BUCKET_NAME: "default-s3-bucket"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "1Gi"
  livenessProbe:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
  readinessProbe:
    httpGet: 
      path: /readiness
      port: 5000
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 2
