#flask
flask:
  image: danielrabi/flaskapp:1.2.5
  replicaCount: 1
  serviceAccount:
    roleArn: ""
  service:
    type: ClusterIP
    port: 80
  containerPort: 5000
  env:
    DB_HOST: mysql-service
    DB_USER: flask
    DB_PASSWORD: flaskpass
    DB_NAME: dog_list
    S3_BUCKET_NAME: dog_list
  resources: {}
  livenessProbe:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
  readinessProbe:
    httpGet: 
      path: /readiness
      port: 5000
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 2